apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvss-service
spec:
  replicas: 1                       # keep 1 until you solve state (see notes below)
  selector:
    matchLabels:
      app: kvss-service
  template:
    metadata:
      labels:
        app: kvss-service
    spec:
      containers:
        - name: romantic-swartz
          image: kvss-service:latest        # if using Option A (built inside minikube). Otherwise use your-registry/kvss:tag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          readinessProbe:
            tcpSocket:
              port: 5050
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"